#define CONTINUE_PROGRAM 'n'
#define MINIMUM_BALANCE_FEE 35
#define SAVINGS_ACCOUNT_MINIMUM_BALANCE 1000
#define CHECKING_ACCOUNT_MINIMUM_BALANCE 500
#define MINIMUM_BALANCE_FEE_CHARGED 1
#define MINIMUM_BALANCE_FEE_NOT_CHARGED 0
#define PERCENT_CONVERSION_FACTOR 100.0
#define NO_MINIMUM_BALANCE 0
